---
- name: package-updates
  hosts: '{{ target }}'
  gather_facts: yes
  vars:
  become: true
  become_user: root
  tasks:
    - name: package updates (redhat)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'Redhat'

    - name: package updates (debian)
      apt:
        update_cache: yes
        upgrade: yes
        name: "*"
        state: latest
